Revert "Do not duplicate resources. Fixes #115"
This reverts commit 4b846333d977b3a2d6281428c15b7e817088594b.

Because the commit breaks running `rake spec` and looks like it breaks where install Pods with `rake pod:install`

```
[master][~/prj/motion-cocoapods]$ rake spec
bundle exec bacon spec/cocoapods_spec.rb
motion-cocoapods
  - pods deployment target should equal to project deployment target
  - sets the Rakefile as the location of the Podfile
  - adds all the system frameworks and libraries [ERROR: NoMethodError]
  - adds a prebuilt (static library) framework to the linked libs [FAILED]
  - installs the Pods to vendor/Pods [FAILED]
  - configures CocoaPods to resolve dependency files for the iOS platform
  - writes Podfile.lock to vendor/ [FAILED]
  - adds Pods.xcodeproj as a vendor project with header dirs including all vendored_frameworks [ERROR: NoMethodError]
  - runs the post_install hook
  - removes Pods.bridgesupport whenever the PODS section of Podfile.lock changes [ERROR: Errno::ENOENT]
  - provides a list of the activated pods on #inspect, which is used in `rake config` [ERROR: NoMethodError]

NoMethodError: undefined method `each' for nil:NilClass
	/Users/watson/prj/motion-cocoapods/lib/motion/project/cocoapods.rb:251:in `install_resources': motion-cocoapods - adds all the system frameworks and libraries
	/Users/watson/prj/motion-cocoapods/lib/motion/project/cocoapods.rb:243:in `install!'
	/Users/watson/prj/motion-cocoapods/lib/motion/project/cocoapods.rb:361:in `block (2 levels) in <top (required)>'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
	/Users/watson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
	spec/cocoapods_spec.rb:63:in `block (2 levels) in <top (required)>'
	spec/cocoapods_spec.rb:69:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

Bacon::Error: [].include?("-force_load '/Users/watson/prj/motion-cocoapods/tmp/vendor/Pods/HockeySDK/Vendor/CrashReporter.framework/CrashReporter'") failed
	spec/cocoapods_spec.rb:79:in `block (2 levels) in <top (required)>': motion-cocoapods - adds a prebuilt (static library) framework to the linked libs
	spec/cocoapods_spec.rb:78:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

Bacon::Error: #<Pathname:/Users/watson/prj/motion-cocoapods/tmp/vendor/Pods/AFNetworking>.exist?() failed
	spec/cocoapods_spec.rb:89:in `block (2 levels) in <top (required)>': motion-cocoapods - installs the Pods to vendor/Pods
	spec/cocoapods_spec.rb:88:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

Bacon::Error: #<Pathname:/Users/watson/prj/motion-cocoapods/tmp/vendor/Podfile.lock>.exist?() failed
	spec/cocoapods_spec.rb:99:in `block (2 levels) in <top (required)>': motion-cocoapods - writes Podfile.lock to vendor/
	spec/cocoapods_spec.rb:98:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

NoMethodError: undefined method `path' for nil:NilClass
	spec/cocoapods_spec.rb:104:in `block (2 levels) in <top (required)>': motion-cocoapods - adds Pods.xcodeproj as a vendor project with header dirs including all vendored_frameworks
	spec/cocoapods_spec.rb:102:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/watson/prj/motion-cocoapods/tmp/vendor/Pods/Pods.bridgesupport
	spec/cocoapods_spec.rb:131:in `initialize': motion-cocoapods - removes Pods.bridgesupport whenever the PODS section of Podfile.lock changes
	spec/cocoapods_spec.rb:131:in `open'
	spec/cocoapods_spec.rb:131:in `open'
	spec/cocoapods_spec.rb:131:in `block (2 levels) in <top (required)>'
	spec/cocoapods_spec.rb:129:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

NoMethodError: undefined method `to_hash' for nil:NilClass
	/Users/watson/prj/motion-cocoapods/lib/motion/project/cocoapods.rb:284:in `inspect': motion-cocoapods - provides a list of the activated pods on #inspect, which is used in `rake config`
	spec/cocoapods_spec.rb:151:in `block (2 levels) in <top (required)>'
	spec/cocoapods_spec.rb:150:in `block in <top (required)>'
	spec/cocoapods_spec.rb:13:in `<top (required)>'

11 specifications (7 requirements), 3 failures, 4 errors
rake aborted!
Command failed with status (1): [bundle exec bacon spec/cocoapods_spec.rb...]
/Users/watson/prj/motion-cocoapods/Rakefile:21:in `block in <top (required)>'
Tasks: TOP => spec
(See full trace by running task with --trace)
```